# Generated by Django 4.2.7 on 2023-11-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=25)),
                ('company', models.CharField(max_length=25)),
                ('experience', models.CharField(max_length=25)),
            ],
        ),
    ]
